dataset: nyc
distance_type: TP
cuda: 0


traj_file: ./data/nyc/st_traj/matching_result.csv
time_file: ./data/nyc/st_traj/time_drop_list.csv


shuffle_node_file: ./data/nyc/st_traj/shuffle_node_list.npy
shuffle_time_file: ./data/nyc/st_traj/shuffle_time_list.npy
shuffle_d2vec_file: ./data/nyc/st_traj/shuffle_d2vec_list.npy
shuffle_coor_file: ./data/nyc/st_traj/shuffle_coor_list.npy
shuffle_kseg_file: ./data/nyc/st_traj/shuffle_kseg_list.npy
kseg: 5


path_node_triplets: ./data/nyc/triplet/TP/node_triplets_2w_STBall
path_time_triplets: ./data/nyc/triplet/TP/time_triplets_2w_STBall
path_d2vec_triplets: ./data/nyc/triplet/TP/d2vec_triplets_2w_STBall

path_triplets_truth: ./ground_truth/nyc/TP/train_triplet_2w_STBall.npy
path_vali_truth: ./ground_truth/nyc/TP/vali_st_distance.npy
path_test_truth: ./ground_truth/nyc/TP/test_st_distance.npy


pointnum:  # The number of nodes in the network
  tdrive: 75000 # Replace this line for your data and node numbers


feature_size: 64   # node2vec feature size
embedding_size: 64 # GCN embedding size
date2vec_size: 64 # date2vec output size
hidden_size: 128  # LSTM hidden size
num_layers: 1    # Spatial LSTM layer
dropout_rate: 0
learning_rate: 0.001
concat: False  # whether concat or pairwise add of two embeddings
epochs: 150
train_batch: 128
test_batch: 500
early_stop: 30


node2vec:
  walk_length: 20
  context_size: 10
  walks_per_node: 10
  num_neg_samples: 1
  p: 1
  q: 1


K: 100